#Configuration for Wind Charge

settings:
  explosionStrength: 5.0
  explosionRadius: 5.0
  projectileSpeed: 2.0
  particles:
    ender: false
    smoke: true
    standard: false

#Configuration for database MySQL
db:
  host: 127.0.0.1
  port: 3306
  database: windhome
  username: root
  password:

#Configuration for teleport (/sethome, /home)
teleport:
  cooldown: 60 #number in ticks
  particle: true
