settings:
  explosionStrength: 5.0
  explosionRadius: 5.0
  projectileSpeed: 2.0
  particles:
    ender: false
    smoke: true
    standard: false
##################################################################################################
##################################################################################################
######################################### MY SQL #################################################
##################################################################################################
##################################################################################################
db:
  host: 127.0.0.1
  port: 3306
  database: windhome
  username: root
  password:
