name: Windhome
version: '${version}'
main: com.windhome.Windhome
api-version: '1.21'
authors: [Stal0]
commands:
  givewindcharger:
    description: Give a Wind Charger special
    usage: /givewindcharger
